= payara-micro-gradle-plugin (inline build script) image:https://travis-ci.org/daggerok/payara-micro-gradle-plugin-build-script.svg?branch=master["Build Status", link="https://travis-ci.org/daggerok/payara-micro-gradle-plugin-build-script"]

__inline build script plugin implementation__

Current project demonstrates regular Gradle functionality usage -
payara-micro maven plugin similar gradle tasks implementation
(`bundle` and `start`)

== remote

.install
[source,groovy]
----
apply from: 'https://raw.githubusercontent.com/daggerok/payara-micro-gradle-plugin-build-script/master/gradle/payara-micro-gradle-plugin.gradle'
defaultTasks 'clean', 'bundle'
----

.usage
[source,bash]
----
./gradlew start
# or
./gradlew bundle
ls ./build | grep 'microbundle'
java -jar build/*-microbundle.jar
----

requirements: expected to be used for war packaged projects

== local

.install link:https://github.com/daggerok/payara-micro-gradle-plugin-build-script/blob/master/gradle/payara-micro-gradle-plugin.gradle[see ./gradle/payara-micro-gradle-plugin.gradle build script file]
[source,groovy]
----
apply(from: project.file('./gradle/payara-micro-gradle-plugin.gradle'))
defaultTasks('clean', 'bundle')
----

.usage (similar to payara-micrio maven plugin)
[source,bash]
----
./gradlew bundle
java -jar build/*-microbundle.jar
# or
./gradlew start
----

== multi-project setup

.install
[source,groovy]
----
project(':multi') {
  // other configurations are skipped...
  apply(from: project.file('../gradle/payara-micro-gradle-plugin.gradle'))

  dependencies {
    providedCompile 'javax:javaee-api:8.0'
  }

  defaultTasks('clean', 'bundle')
}
----

.usage
[source,bash]
----
./gradlew start --parallel

# or:

./gradlew clean bundle
java -jar ./build/*-microbundle.jar &
java -jar ./nulti/build/*-microbundle.jar &
----

== build, run and test

.build
[source,bash]
----
./gradlew clean bundle
----

.run (with remote debug for example)
[source,bash]
----
./gradle start
# or debug:
java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005  -Djava.net.preferIPv4Stack=true ./build/*-microbundle.jar
----

.test: post new data
[source,bash]
----
http :8080 string=one
http :8080 string=two
http :8080 string=3
----

[source,http]
----
HTTP/1.1 202 Accepted
Content-Length: 0
Server: Payara Micro #badassfish
X-Frame-Options: SAMEORIGIN
----

[source,bash]
----
http :8080
----

[source,http]
----
HTTP/1.1 200 OK
Content-Length: 17
Content-Type: application/json
Server: Payara Micro #badassfish
X-Frame-Options: SAMEORIGIN
----

[source,json]
----
[
    "two",
    "one",
    "3"
]
----

== my other payara-related repositories

* link:https://github.com/daggerok/kotlin-payara-micro-profile[GitHub: daggerok/kotlin-payara-micro-profile]
* link:https://github.com/daggerok/payara-micro-gradle-no-plugin[GitHub: daggerok/payara-micro-gradle-no-plugin]
* link:https://github.com/daggerok/payara-micro-gradle-plugin-build-script[GitHub: daggerok/payara-micro-gradle-plugin-build-script]
* link:https://github.com/daggerok/maven-java-projects[GitHub: daggerok/maven-java-projects]
* link:https://github.com/daggerok/generator-jvm[GitHub: daggerok/generator-jvm]
* link:https://github.com/daggerok/payara-micro-example[GitHub: daggerok/payara-micro-example]
* link:https://github.com/daggerok/microprofile-examples[GitHub: daggerok/microprofile-examples]
